import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    imgURL:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-se-family-select-202203_GEO_EMEA?wid=940&hei=1112&fmt=jpeg&qlt=90&.v=1646070492835",
    isBestSeller: false,
    outOfStock: true,
    title: "APPLE iPhone SE (Red/White/Black, 64 GB)",
    price: "39900",
    discountPrice: "30449",
    discountPercent: 24,
    rating: 3,
    newArrivals: false,
    description:
      "This iPhone box does not include a power adapter and EarPods.",
    categoryName: "Mobile",
  },
  {
    _id: uuid(),
    imgURL:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-pro-green-select?wid=940&hei=1112&fmt=png-alpha&.v=1644969385505",
    isBestSeller: false,
    outOfStock: false,
    title: "APPLE iPhone 13 (Green, 128 GB)",
    price: "79900",
    discountPrice: "74900",
    discountPercent: 6,
    rating: 2,
    newArrivals: false,
    description: "",
    categoryName: "Mobile",
  },
  {
    _id: uuid(),
    imgURL:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-12-white-select-2020?wid=940&hei=1112&fmt=png-alpha&.v=1604343705000",
    isBestSeller: true,
    outOfStock: false,
    title: "APPLE iPhone 12 (White, 64 GB)",
    price: "65900",
    discountPrice: "59999",
    discountPercent: 9,
    rating: 5,
    newArrivals: false,
    description: "",
    categoryName: "Mobile",
  },
  {
    _id: uuid(),
    imgURL:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone11-select-2019-family_GEO_EMEA?wid=882&hei=1058&fmt=jpeg&qlt=90&.v=1567022219953",
    isBestSeller: true,
    outOfStock: false,
    title: "APPLE iPhone 11 (White, 64 GB)",
    price: "49990",
    discountPrice: "47990",
    discountPercent: 4,
    rating: 5,
    newArrivals: true,
    description: "",
    categoryName: "Mobile",
  },
  {
    _id: uuid(),
    imgURL:
      "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto,fl_lossy,c_fill,g_auto/b187f37da5574492b89ba8dd008c6db2_9366/B43665_01_standard.jpg",
    isBestSeller: true,
    outOfStock: false,
    title: "Easy Vulc 2.0 Shoes",
    price: "4599",
    discountPrice: "2759",
    discountPercent: 39,
    rating: 4,
    newArrivals: false,
    description: "",
    categoryName: "Shoes",
  },
  {
    _id: uuid(),
    imgURL:
      "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto,fl_lossy,c_fill,g_auto/4d72ef237e784acc993ead1a00a3f515_9366/H00534_01_standard.jpg",
    isBestSeller: true,
    outOfStock: false,
    title: "Advantage Base Shoes",
    price: "4999",
    discountPrice: "2999",
    discountPercent: 39,
    rating: 1,
    newArrivals: false,
    description: "",
    categoryName: "Shoes",
  },
  {
    _id: uuid(),
    imgURL:
      "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto,fl_lossy,c_fill,g_auto/cbb4a936a85b450a97f7ad4000f57d32_9366/H02030_01_standard.jpg",
    isBestSeller: true,
    outOfStock: false,
    title: "Grand Court SE Shoes",
    price: "6599",
    discountPrice: "3959",
    discountPercent: 39,
    rating: 2,
    newArrivals: false,
    description: "",
    categoryName: "Shoes",
  },
  {
    _id: uuid(),
    imgURL:
      "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2e4a82808da48268f24a8dd008c84cc_9366/easy-vulc-2.0-shoes.jpg",
    isBestSeller: true,
    outOfStock: false,
    title: "Easy Vulc 2.0 Shoes",
    price: "4599",
    discountPrice: "2759",
    discountPercent: 40,
    rating: 3,
    newArrivals: true,
    description: "",
    categoryName: "Shoes",
  },
  {
    _id: uuid(),
    imgURL:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MKUQ3_VW_34FR+watch-45-alum-midnight-nc-7s_VW_34FR_WF_CO?wid=750&hei=712&trim=1%2C0&fmt=p-jpg&qlt=95&.v=1632171067000%2C1631661671000",
    isBestSeller: true,
    outOfStock: false,
    title:
      "APPLE Watch Series 7 GPS + Cellular, MKJP3HN/A 45 mm Aluminium Case",
    price: "53900",
    discountPrice: "51000",
    discountPercent: 5,
    rating: 4,
    newArrivals: false,
    description: "",
    categoryName: "Watches",
  },
  {
    _id: uuid(),
    imgURL:
      "https://www.reliancedigital.in//medias/realme-RMA161-Smart-Watches-491946585-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wxODM3MjN8aW1hZ2UvanBlZ3xpbWFnZXMvaDFlL2gxMS85NDcxNTY4MzE0Mzk4LmpwZ3wwMTE0ZGIxNTMzZDdjOGE1ZmE1MmUyZDg2MjI0NDdmNDE2ZjhmM2QxMzExNjFiMTkzYzIyNjdkOWQ0OWJhN2Iw",
    isBestSeller: true,
    outOfStock: false,
    title:
      "realme RMA161 Fashion Strap Smart Watch, Black , 14 Sports Mode, Water Resistant",
    price: "6999",
    discountPrice: "3999",
    discountPercent: 43,
    rating: 1,
    newArrivals: false,
    description: "",
    categoryName: "Watches",
  },
  {
    _id: uuid(),
    imgURL:
      "https://www.reliancedigital.in/medias/boAt-Watch-Xtend-Smartwatch-491998423-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wyMDA4OTJ8aW1hZ2UvanBlZ3xpbWFnZXMvaGI1L2g5NS85NjUzOTE3ODEwNzE4LmpwZ3xmMWRkMDlmN2FhNGQ5YTAzZGQ4NGE5MDM3ZTg1YThlYmQ2NzcyNGU1NTMwNjRkZTk1NTE2OTYwNjBlM2E1YzMw",
    isBestSeller: true,
    outOfStock: false,
    title:
      "boAt Watch‌ Xtend RTL 4.29 cm (1.69 Inch) Smartwatch with Built-In Alexa Voice Assistant, Sandy Cream",
    price: "7990",
    discountPrice: "3499",
    discountPercent: 56,
    rating: 2,
    newArrivals: false,
    description: "",
    categoryName: "Watches",
  },
  {
    _id: uuid(),
    imgURL:
      "https://www.reliancedigital.in/medias/Samsung-Gear-S3-Frontier-SM-R760N-Smart-Watch-Dark-Gray-491315697-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w0OTkwMjF8aW1hZ2UvcG5nfGltYWdlcy9oYjAvaGUxLzg5MzMwNjg3MDE3MjYucG5nfGM5ZmM4MTk4ZTA4OWFiNzZiZGQwOGFjNGM0OGQxMWQwMTY2NWI5NmViOWEyNTMyYjNjY2RmZjIwYmQwNWRhOWY",
    isBestSeller: true,
    outOfStock: false,
    title: "Samsung Gear S3 Frontier SM-R760N Smart Watch, Dark Gray",
    price: "29999",
    discountPrice: "28500",
    discountPercent: 4,
    rating: 3,
    newArrivals: true,
    description: "",
    categoryName: "Watches",
  },
  {
    _id: uuid(),
    imgURL: "https://m.media-amazon.com/images/I/61+3f5q7T6S._SX679_.jpg",
    isBestSeller: true,
    outOfStock: false,
    title:
      "realme Buds Wireless 2 Neo Bluetooth in Ear Earphones with Mic (Black)",
    price: "2499",
    discountPrice: "1499",
    discountPercent: 40,
    rating: 5,
    newArrivals: false,
    description: "",
    categoryName: "Headphones",
  },
  {
    _id: uuid(),
    imgURL: "https://m.media-amazon.com/images/I/51wnOfRKl6L._SL1500_.jpg",
    isBestSeller: true,
    outOfStock: false,
    title: "Sony WF-C500 Truly Wireless Bluetooth Earbuds Music– Orange",
    price: "29999",
    discountPrice: "28500",
    discountPercent: 4,
    rating: 4,
    newArrivals: false,
    description: "",
    categoryName: "Headphones",
  },
  {
    _id: uuid(),
    imgURL: "https://m.media-amazon.com/images/I/41oEEpCeNUL._SX679_.jpg",
    isBestSeller: true,
    outOfStock: false,
    title: "Apple EarPods with Lightning Connector",
    price: "1900",
    discountPrice: "1679",
    discountPercent: 12,
    rating: 4,
    newArrivals: false,
    description: "",
    categoryName: "Headphones",
  },
  {
    _id: uuid(),
    imgURL: "https://m.media-amazon.com/images/I/61n1aLvbaDL._SX522_.jpg",
    isBestSeller: true,
    outOfStock: false,
    title:
      "Ambrane Dots 38 Bluetooth Truly Wireless in Ear Earbuds with Mic (Green)",
    price: "2499",
    discountPrice: "900",
    discountPercent: 60,
    rating: 2,
    newArrivals: true,
    description: "",
    categoryName: "Headphones",
  },
];
