export const GET_PRODUCTS = "GET_PRODUCTS";
export const FILTER_BY_RATING = "FILTER_BY_RATING";
export const HIGH_TO_LOW = "HIGH_TO_LOW";
export const LOW_TO_HIGH = "LOW_TO_HIGH";
export const FILTER_BY_RANGE = "FILTER_BY_RANGE";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const GET_MAX_PRICE = "GET_MAX_PRICE";
export const PRICE_RANGE = "PRICE_RANGE";
export const GET_CATEGORY = "GET_CATEGORY";

// Cart Actions

export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_CART_QUANTITY = "INCREMENT_CART_QUANTITY";
export const DECREMENT_CART_QUANTITY = "DECREMENT_CART_QUANTITY";
export const DELETE_CART_QUANTITY = "DELETE_CART_QUANTITY";
